language: python

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

python:
  - '2.7'
  - 'pypy'
  - '3.5'

install:
  - pip install tox>=1.8
  - pip install codecov
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then pip install pycrypto; fi

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - COVERAGE_PROCESS_START=gluon/tests/coverage.ini

before_script:
  - mysql -e 'create database pydal;'
  - psql -c 'create database pydal;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d pydal;
  - psql -c 'SHOW SERVER_VERSION' -U postgres

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

after_success:
  - tox -e coverage
  - codecov

notifications:
  email: true

addons:
  postgresql: "9.4"
